In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# upload the Excel file
from google.colab import files
uploaded = files.upload()

Saving dim_date_2022_2025.csv to dim_date_2022_2025.csv
Saving dim_product.csv to dim_product.csv
Saving dim_region.csv to dim_region.csv
Saving dim_supplier.csv to dim_supplier.csv
Saving dim_warehouse.csv to dim_warehouse.csv
Saving fact_orders_800_rows.csv to fact_orders_800_rows.csv

In [3]:
#loading all files into pandas
fact=pd.read_csv("fact_orders_800_rows.csv")
product=pd.read_csv("dim_product.csv")
region=pd.read_csv("dim_region.csv")
supplier=pd.read_csv("dim_supplier.csv")
warehouse=pd.read_csv("dim_warehouse.csv")
date=pd.read_csv("dim_date_2022_2025.csv")

In [4]:
# checking shape of all fiels
print("Fact shape:", fact.shape)
print("Product shape:", product.shape)
print("Region shape:", region.shape)
print("Supplier shape:", supplier.shape)
print("Warehouse shape:", warehouse.shape)
print("Date shape:", date.shape)

Fact shape: (800, 13)
Product shape: (8, 7)
Region shape: (5, 7)
Supplier shape: (25, 5)
Warehouse shape: (5, 5)
Date shape: (1461, 7)

In [5]:
fact.head()

,order_id,order_date,product_id,region_id,warehouse_id,supplier_id,quantity_ordered,quantity_supplied,unit_price,transport_cost,operational_cost,delivery_status,delay_days
0,ORD0001,2025-08-02,P1,R1,W1,S24,889,800,23,2209,1564,On-time,0
1,ORD0002,2022-03-07,P1,R1,W1,S7,288,230,28,1451,1619,Delayed,3
2,ORD0003,2023-07-24,P1,R2,W2,S23,501,501,25,1189,1478,On-time,0
3,ORD0004,2022-07-18,P3,R3,W3,S20,421,378,16,1600,1987,On-time,0
4,ORD0005,2025-06-20,P3,R5,W5,S7,831,581,19,1778,1269,Delayed,2

In [6]:
product.head()

,product_id,product_name,category,price_sensitivity,demand_pattern,shelf_life_days,profit_margin_type
0,P1,Tomato,Vegetable,High,Seasonal,7,Low
1,P2,Onion,Vegetable,Medium,Stable,30,Medium
2,P3,Potato,Vegetable,Low,Stable,60,Medium
3,P4,Banana,Fruit,High,Seasonal,5,Low
4,P5,Apple,Fruit,Medium,Seasonal,20,High

In [7]:
region.head()

,region_id,region_name,demand_level,delay_risk,cost_level,infrastructure_quality,supply_volatility
0,R1,Bangalore,High,Low,Medium,Good,High
1,R2,Hyderabad,Medium,Medium,Medium,Moderate,Medium
2,R3,Chennai,Medium,High,Low,Poor,High
3,R4,Mumbai,High,Low,High,Good,Low
4,R5,Delhi,Very High,Medium,High,Moderate,Medium

In [8]:
supplier.head()

  supplier_id supplier_name region_id reliability supply_capacity
0          S1      Farmer_1        R3         Low             Low
1          S2      Farmer_2        R2         Low          Medium
2          S3      Farmer_3        R5         Low             Low
3          S4      Farmer_4        R5         Low            High
4          S5      Farmer_5        R4        High          Medium

In [9]:
warehouse.head()

  warehouse_id warehouse_name region_id efficiency_level delay_risk
0           W1        BLR Hub        R1             High        Low
1           W2        HYD Hub        R2           Medium     Medium
2           W3        CHE Hub        R3              Low       High
3           W4        MUM Hub        R4             High        Low
4           W5        DEL Hub        R5           Medium     Medium

In [10]:
date.head()

         date  year    month  month_number quarter    weekday  week_number
0  2022-01-01  2022  January             1      Q1   Saturday           52
1  2022-01-02  2022  January             1      Q1     Sunday           52
2  2022-01-03  2022  January             1      Q1     Monday            1
3  2022-01-04  2022  January             1      Q1    Tuesday            1
4  2022-01-05  2022  January             1      Q1  Wednesday            1

In [11]:
#chakimg for null values
print("fact null values: ",fact.isnull().sum())
print("product null values: \n",product.isnull().sum())
print("region null values: \n",region.isnull().sum())
print("supplier null values: \n",supplier.isnull().sum())
print("warehouse null values: \n",warehouse.isnull().sum())

fact null values:  order_id             0
order_date           0
product_id           0
region_id            0
warehouse_id         0
supplier_id          0
quantity_ordered     0
quantity_supplied    0
unit_price           0
transport_cost       0
operational_cost     0
delivery_status      0
delay_days           0
dtype: int64
product null values:
 product_id            0
product_name          0
category              0
price_sensitivity     0
demand_pattern        0
shelf_life_days       0
profit_margin_type    0
dtype: int64
region null values:
 region_id                 0
region_name               0
demand_level              0
delay_risk                0
cost_level                0
infrastructure_quality    0
supply_volatility         0
dtype: int64
supplier null values:
 supplier_id        0
supplier_name      0
region_id          0
reliability        0
supply_capacity    0
dtype: int64
warehouse null values:
 warehouse_id        0
warehouse_name      0
region_id           0
efficiency_level    0
delay_risk          0
dtype: int64

### **merge data**

In [12]:
fact.columns

Index(['order_id', 'order_date', 'product_id', 'region_id', 'warehouse_id',
       'supplier_id', 'quantity_ordered', 'quantity_supplied', 'unit_price',
       'transport_cost', 'operational_cost', 'delivery_status', 'delay_days'],
      dtype='object')

In [13]:
# convert order_date and date into same formate
fact["order_date"] = pd.to_datetime(fact["order_date"]).dt.date
date["date"] = pd.to_datetime(date["date"]).dt.date

In [14]:
#merge the all datsets
df = fact.merge(product, on="product_id", how="left") \
         .merge(region, on="region_id", how="left") \
         .merge(supplier, on="supplier_id", how="left") \
         .merge(warehouse, on="warehouse_id", how="left") \
         .merge(date, left_on="order_date", right_on="date", how="left")

### **data cleaning**

In [15]:
# removing duplicates
df=df.drop_duplicates()

In [16]:
# chaking missing values
df.isnull().sum()

order_id                  0
order_date                0
product_id                0
region_id_x               0
warehouse_id              0
supplier_id               0
quantity_ordered          0
quantity_supplied         0
unit_price                0
transport_cost            0
operational_cost          0
delivery_status           0
delay_days                0
product_name              0
category                  0
price_sensitivity         0
demand_pattern            0
shelf_life_days           0
profit_margin_type        0
region_name               0
demand_level              0
delay_risk_x              0
cost_level                0
infrastructure_quality    0
supply_volatility         0
supplier_name             0
region_id_y               0
reliability               0
supply_capacity           0
warehouse_name            0
region_id                 0
efficiency_level          0
delay_risk_y              0
date                      0
year                      0
month                     0
month_number              0
quarter                   0
weekday                   0
week_number               0
dtype: int64

In [17]:
# hndel missing values
df=df.dropna()

In [18]:
# fix data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 40 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                800 non-null    object
 1   order_date              800 non-null    object
 2   product_id              800 non-null    object
 3   region_id_x             800 non-null    object
 4   warehouse_id            800 non-null    object
 5   supplier_id             800 non-null    object
 6   quantity_ordered        800 non-null    int64
 7   quantity_supplied       800 non-null    int64
 8   unit_price              800 non-null    int64
 9   transport_cost          800 non-null    int64
 10  operational_cost        800 non-null    int64
 11  delivery_status         800 non-null    object
 12  delay_days              800 non-null    int64
 13  product_name            800 non-null    object
 14  category                800 non-null    object
 15  price_sensitivity       800 non-null    object
 16  demand_pattern          800 non-null    object
 17  shelf_life_days         800 non-null    int64
 18  profit_margin_type      800 non-null    object
 19  region_name             800 non-null    object
 20  demand_level            800 non-null    object
 21  delay_risk_x            800 non-null    object
 22  cost_level              800 non-null    object
 23  infrastructure_quality  800 non-null    object
 24  supply_volatility       800 non-null    object
 25  supplier_name           800 non-null    object
 26  region_id_y             800 non-null    object
 27  reliability             800 non-null    object
 28  supply_capacity         800 non-null    object
 29  warehouse_name          800 non-null    object
 30  region_id               800 non-null    object
 31  efficiency_level        800 non-null    object
 32  delay_risk_y            800 non-null    object
 33  date                    800 non-null    object
 34  year                    800 non-null    int64
 35  month                   800 non-null    object
 36  month_number            800 non-null    int64
 37  quarter                 800 non-null    object
 38  weekday                 800 non-null    object
 39  week_number             800 non-null    int64
dtypes: int64(10), object(30)
memory usage: 250.1+ KB

## **feature engineering**

In [20]:
# convert date time into int format
df["order_date"] = pd.to_datetime(df["order_date"])

In [21]:
# extract date features
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["day"] = df["order_date"].dt.day
df["weekday"] = df["order_date"].dt.weekday

In [22]:
# selecting target columns
y=df["quantity_ordered"]  #for demand

In [58]:
# for x
x = df[["unit_price",
    "transport_cost",
    "operational_cost",
    "delay_days",
    "year",
    "month",
    "weekday"
]]

In [59]:
print("x :",x.head())
print("y :",y.head())

x :    unit_price  transport_cost  operational_cost  delay_days  year  month  \
0          23            2209              1564           0  2025      8
1          28            1451              1619           3  2022      3
2          25            1189              1478           0  2023      7
3          16            1600              1987           0  2022      7
4          19            1778              1269           2  2025      6

   weekday
0        5
1        0
2        0
3        0
4        4
y : 0    889
1    288
2    501
3    421
4    831
Name: quantity_ordered, dtype: int64

### **train test split**

In [61]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

## **train model**

In [62]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)
model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [63]:
# prediction
y_pred = model.predict(x_test)

### **evaliuate model**

In [64]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2=r2_score(y_test,y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 score:",r2)

MAE: 62.0216875
MSE: 6506.084798124999
R2 score: 0.8811422772436983

### **xgboost**

In [65]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [66]:
# train model
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

xgb_model.fit(x_train, y_train)

# prediction
y_pred_xgb = xgb_model.predict(x_test)

In [67]:
# evaluate the model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
r2_xgb = r2_score(y_test, y_pred_xgb)

print("XGBoost Results")
print("MAE:", mae_xgb)
print("MSE:", mse_xgb)
print("R2 Score:", r2_xgb)

XGBoost Results
MAE: 66.01053619384766
MSE: 7175.4326171875
R2 Score: 0.8689141273498535

## **creating predict dataset**

In [68]:
future_df=df.copy()

In [69]:
# convert date
future_df["order_date"]=pd.to_datetime(future_df["order_date"])

In [81]:
# shift date to future date
future_df["order_date"] = future_df["order_date"].apply(lambda x: x.replace(year=2026))

In [82]:
# creating date features
future_df["year"] = future_df["order_date"].dt.year
future_df["month"] = future_df["order_date"].dt.month
future_df["weekday"] = future_df["order_date"].dt.weekday

In [83]:
# adding quantity order
future_df["quantity_ordered"] = future_df["quantity_ordered"] * 1.05
future_df["unit_price"] = future_df["unit_price"] * 1.03

In [84]:
# prepare features
future_features=future_df.reindex(columns=x.columns)

# fill missing values
future_features=future_features.fillna(0)

In [85]:
# predict future demand
future_df["predicted_demand"] = model.predict(future_features)

In [90]:
# selecting only important columns for dataset
final_df = future_df[[
    "product_id",
    "product_name",
    "region_id",
    "region_name",
    "warehouse_id",
    "warehouse_name",
    "order_date",
    "quantity_ordered",
    "quantity_supplied",
    "predicted_demand"
]]

In [91]:
# rename the columns
final_df = final_df.rename(columns={
    "order_date": "predict_Date",
    "quantity_ordered": "Actual_Demand",
    "quantity_supplied": "Supply",
    "predicted_demand": "Predicted_Demand"
})

In [92]:
# remove the duplicate
final_df=final_df.drop_duplicates()

In [93]:
# save predict dataset csv file
final_df.to_csv("predict dataset final 1.csv",index=False)